# Generated by Django 4.0.2 on 2022-02-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_service_ppoi_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subdescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=225)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.service')),
            ],
        ),
    ]
