# Generated by Django 4.0.2 on 2022-02-03 04:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_update_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
