# Generated by Django 4.0.2 on 2022-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_client_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('company', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=225)),
                ('ad_type', models.CharField(choices=[('outdoor_advertising', 'outdoor_advertising'), ('agent_partnership', 'agent_partnership')], max_length=128)),
            ],
        ),
    ]
