# Generated by Django 3.2.8 on 2022-02-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ad_type',
            field=models.CharField(choices=[('outdoor_advertising', 'outdoor_advertising'), ('agent_partnership', 'agent_partnership')], default='outdoor_advertising', max_length=128),
        ),
    ]
