# Generated by Django 3.2.8 on 2022-02-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_alter_contact_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
