# Generated by Django 3.2.8 on 2022-02-04 10:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_update_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.CharField(default=1, max_length=355),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
